name: Install dependencies
description: Install dependencies specified in .tool-versions file using asdf

inputs:
  asdf_version:
    description: The asdf version to install
    required: true

runs:
  using: composite
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@1902764435ca0dd2f3388eea723a4f92a4eb8302
      with:
        asdf_version: ${{ inputs.asdf_version }}

    - name: Cache asdf
      uses: actions/cache@v4
      with:
        path: |
          ~/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}

    - name: Install asdf dependencies in .tool-versions
      uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302
      with:
        asdf_version: ${{ inputs.asdf_version }}
      env:
        PYTHON_CONFIGURE_OPTS: --enable-shared

    - name: Cache python venv
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}

    - name: Setup python venv
      shell: bash
      run: make install
