name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions: {}
jobs:
  pr_title_format_check:
    name: PR Title Format Check
    uses: NHSDigital/eps-common-workflows/.github/workflows/pr_title_check.yml@ba4bcd7fa2367cc44c9078adb96a654236d3691a
    permissions:
      pull-requests: write
  get_config_values:
    uses: NHSDigital/eps-common-workflows/.github/workflows/get-repo-config.yml@ba4bcd7fa2367cc44c9078adb96a654236d3691a
    permissions:
      attestations: read
      contents: read
      packages: read
    with:
      verify_published_from_main_image: false

  quality_checks:
    name: Quality Checks
    needs: get_config_values
    uses: NHSDigital/eps-common-workflows/.github/workflows/quality-checks-devcontainer.yml@889349f9d93e4846a642f7973b7c26b180bec5aa
    permissions:
      contents: read
      id-token: write
      packages: read
    with:
      pinned_image: ${{ needs.get_config_values.outputs.pinned_image }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
